# Generated by Django 3.1.6 on 2021-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('full_desc', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата сдачи')),
                ('pins', models.FileField(upload_to='homework/', verbose_name='Прикреплённый документ')),
                ('score', models.CharField(choices=[('1', '10'), ('2', '20'), ('3', '30'), ('4', '40')], max_length=1)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
