# Generated by Django 3.1.6 on 2021-02-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_service', '0002_auto_20210210_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(to='diary_service.Subject'),
        ),
    ]
