# Generated by Django 3.1.6 on 2021-02-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_service', '0003_group_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='pins',
            field=models.FileField(blank=True, null=True, upload_to='homework/', verbose_name='Прикреплённый документ'),
        ),
    ]
