# Generated by Django 3.1.6 on 2021-02-10 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comm_service', '0002_auto_20210210_1242'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profile_service', '0001_initial'),
        ('report_service', '0001_initial'),
        ('diary_service', '0002_auto_20210210_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stats',
            field=models.ManyToManyField(blank=True, related_name='_student_stats_+', to='report_service.StatElement'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='diary_service.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='chats',
            field=models.ManyToManyField(blank=True, to='comm_service.Chat'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
