# Generated by Django 3.1.6 on 2021-02-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_service', '0002_auto_20210210_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
