# Generated by Django 3.1.6 on 2021-02-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary_service', '0004_auto_20210214_0919'),
        ('news_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subject_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='diary_service.subject'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary_service.subject'),
        ),
    ]
