# Generated by Django 3.1.6 on 2021-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0002_auto_20210214_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('rp', 'Замена'), ('nw', 'Новое'), ('an', 'Объявление')], max_length=2, verbose_name='Тип'),
        ),
    ]
