# Generated by Django 3.1.6 on 2021-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_service', '0003_auto_20210213_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='replays_to',
            new_name='replies_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время'),
        ),
    ]
