# Generated by Django 3.1.6 on 2021-02-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_service', '0001_initial'),
        ('diary_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('1', 'ОТ'), ('2', 'УП'), ('3', 'ОП'), ('4', '2'), ('5', '3'), ('6', '4'), ('7', '5')], max_length=2)),
                ('score', models.CharField(blank=True, choices=[('1', '10'), ('2', '20'), ('3', '30'), ('4', '40')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_service.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary_service.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_service.teacher')),
            ],
            options={
                'verbose_name': 'Элемент статистики',
                'verbose_name_plural': 'Элементы статистики',
            },
        ),
    ]
